server:
  port: 8765

eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    home-page-url-path: /
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id:  ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    hostname: ${spring.cloud.client.hostname}
    # docker 部署开启
  #        prefer-ip-address: true
  #        ip-address: localhost
  client:
    serviceUrl:
      #            defaultZone: http://localhost:8761/eureka/
      # docker 部署开启
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
spring:
  application:
    name: gateway
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
    database: 2
    host: 192.168.1.222
    jedis:
      pool:
        max-active: 20
  #  rabbitmq:
  #      host: ${RABBIT_MQ_HOST:localhost}
  #      port:  ${RABBIT_MQ_PORT:5672}
  #      username: guest
  #      password: guest
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        # =====================================
        - id: auth
          uri: lb://auth
          order: 8000
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: admin
          uri: lb://admin
          order: 8001
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=2
        - id: MIT-Cloud
          uri: lb://MIT-Cloud
          order: 8002
          predicates:
            - Path=/api/mitc/**
          filters:
            - StripPrefix=2
        - id: community-yingtan
          uri: lb://community-yingtan
          order: 8003
          predicates:
            - Path=/api/communityyingtan/**
          filters:
            - StripPrefix=2


logging:
  level:
    com.mit.gate: info

management:
  endpoints:
    web:
      exposure:
        include: '*'
      security:
        enabled: false


gate:
  ignore:
    startWith: /auth/jwt


auth:
  serviceId: auth
  user:
    token-header: Authorization
  client:
    token-header: x-client-token
    #不填则默认读取spring.application.name
    id: gate
    secret: 123456
